### ISSUE TITLE
Header: Icon color not changing

### ISSUE THREAD

**Issue by hAMMERlized** [neilimixamo/Home-Assistant-Quick-Look-Mobile#12]
I have recognized that the icons and the color in the header do nitnxhangr when activating a climate entity. I have filled the ```air_heating_yaml```
with my entities but nothing happens. No matter what mode I am running them (auto, heat or cool).

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/95163968/4b39a753-731d-4327-8459-ecd0c94c86d7)

**Comment by hAMMERlized** [comment]
Sorry my fault. Fixed it myself.

**Comment by AndyPanerai** [comment]
> Sorry my fault. Fixed it myself.

How did you fix it ?
I'm having the same issue

**Comment by hAMMERlized** [comment]
Tbh I am not sure anymore but I think I forgot the `''` in the `some climates_are_on.yaml` where you type the entities in.

For example first I had climate.your_climate instead of `'climate.your_climate`

**Comment by AndyPanerai** [comment]
> Tbh I am not sure anymore but I think I forgot the `''` in the `some climates_are_on.yaml` where you type the entities in.
> 
> For example first I had `climate.your_climate` instead of `'climate.your_climate'`.

Thank you, i have tried it (with lights) but nothing is changed, the header icons still dont have any colour when some ligths are on.
