### ISSUE TITLE
Cover Icon not work 

### ISSUE THREAD

**Issue by xADDRx** [neilimixamo/Home-Assistant-Quick-Look-Mobile#16]
Hi,

thanks for this great configuration!

So far everything works, but the roller shutter icon is not displayed correctly for me. Maybe I'm doing something wrong too?

`         - type: custom:button-card # ENTITY 07
            template: cover
            variables:
              entity: cover.roller_shutter_3_7
              name: Badezimmer
              battery: #optional battery sensor to display as a badge when <60%
              expand_to: #required if cover_expandable template is used`

![grafik](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/64784940/ba9e42b1-9c38-491f-bccb-6125f2238edb)

![grafik](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/64784940/2f9e9314-fca1-473e-8423-605b67105231)

**Comment by kesm** [comment]
I have the same issue, if I change the icon manually on your second screenshot it's ok but I don't have the icon changing if the cover is open or closed

**Comment by neilimixamo** [comment]
Hi guys, I have made updates to cover.yaml and cover_expandable.yaml files, bringing them to version 2.0.1. This update addresses the icon issue you pointed. Now the cards will display different icons based on their open or closed states. If you wish to customize those icons, you can do so by modifying lines 33 and 35 in the respective files. 

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/c4796a8b-c248-46f1-9531-18c4aa4e0c91)

**Comment by xADDRx** [comment]
Thank you!!!
