### ISSUE TITLE
Add link to the new to do entities in bottom bar

### ISSUE THREAD

**Issue by kesm** [neilimixamo/Home-Assistant-Quick-Look-Mobile#22]
With latest home assistant update (20203.11) there is now a to do entities [Home Assistant Release Note](https://www.home-assistant.io/blog/2023/11/01/release-202311/#there-is-a-lot-to-do) . I would like to be able to access it through bottom bar, instead of notifications for example.

Do you know if it's possible to do this?

**Comment by neilimixamo** [comment]
Absolutely, you can replace the bottom notification button by a todo button just by adding the following path to line 115 in ` /dashboards/quick_look_mobile/templates/layout/menu.yaml` 

```yaml
navigation_path: /todo
```

Make sure to customize the name and icon of this button as per your preference.

**Comment by kesm** [comment]
Works perfectly, thank you!
