### ISSUE TITLE
mapping values are not allowed here in "/config/dashboards/quick_look_mobile/./views/3.1_air_heating (v1.0).yaml", line 70, column 25

### ISSUE THREAD

**Issue by kesm** [neilimixamo/Home-Assistant-Quick-Look-Mobile#4]
First of all thank you for sharing your code.

I tried to add it to my home assistant instance but got this error when I try to view the new dashboard
 
![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/6907912/11e695ce-a5d8-4f61-a9ce-dd67487e8241)
`mapping values are not allowed here in "/config/dashboards/quick_look_mobile/./views/3.1_air_heating (v1.0).yaml", line 70, column 25`

Here is the content of my configuration.yaml: 

```# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
     # Add the IP address of the proxy server
    - xxx/24  # You may also provide the subnet mask

frontend:
  themes: !include_dir_merge_named themes/

lovelace:
  mode: storage
  dashboards: !include dashboards/dashboards.yaml
  
sensor: !include_dir_list entities/sensors/
    
# Example configuration.yaml entry
google_assistant:
  project_id: xxx
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
 ```
 

I tried to clear my cache but it doesn't solved the issue

Home Assistant 2023.6.2
Interface utilisateur : 20230608.0 - latest

**Comment by hAMMERlized** [comment]
Maybe you should simply read the error. Open up the air_heating.yaml with studio code server and you'll see the error. There is a little typo in that file which  @neilimixamo has to fix. Fix it and you are ready to go.

<img width="1440" alt="Bildschirmfoto 2023-06-24 um 02 08 13" src="https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/95163968/6f393f9f-0cfe-426f-9703-0c246c6cd997">
<img width="1440" alt="Bildschirmfoto 2023-06-24 um 02 07 41" src="https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/95163968/64483f12-5fd9-452d-b3a8-374d31f883a9">

**Comment by neilimixamo** [comment]
Hi @kesm, as pointed out by @hAMMERlized , the error is due to a misplaced colon (the one on line 69 shifted to line 70, causing duplication). You can easily correct the error manually or simply download the updated 1.1 version, especially intended for future new users. Thank you for bringing it to my attention, and I hope the dashboard will work perfectly afterwards.

**Comment by kesm** [comment]
Thanks for the help, it's ok now!
