### ISSUE TITLE
Badge icon for entities count

### ISSUE THREAD

**Issue by hAMMERlized** [neilimixamo/Home-Assistant-Quick-Look-Mobile#7]
And me again. How about a badge icon or something similar in the header menu besides the main icons to quickly see how man lights, climates (e.g. air conditioners) are currently on without need to go in the sub menu / light section etc.

**Comment by neilimixamo** [comment]
Having badges in the Header view could be a great idea. It wouldn't be an issue for me with the Lights view, but I'm unsure about how to proceed with other views like the Air view, where the icon will change based on the active devices. For example, if it's displaying a thermometer icon, the badge could show the number of climates turned on, and if it's a fan icon, it could display the the number of fans turned on. However, the view won't be capable of showing those two badges simultaneously. Would this be ok for you ?

**Comment by neilimixamo** [comment]
Header badges will be visible by default with a new variable `show_badge` to disable them with `false` if needed

![badges light](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/7e8cb2d1-09fc-4e5f-8d3f-c4bd36068c0f)
![badges dark](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/181e25cc-9009-4e8c-9635-aff7d53b3677)

**Comment by hAMMERlized** [comment]
Nice one! What about putting the badgets on the corner of the custom card itself? Like this the icon wouldn't be covered. Just an idea.

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/95163968/3a1d709f-93ec-4307-ac53-e6c2dc4df9f4)

**Comment by neilimixamo** [comment]
That's true, but it may be challenging to make them overflow outside their respective cards. I will explore what options are available and see what I can do.

**Comment by neilimixamo** [comment]
You're right, it looks much cleaner at the corner :)

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/9d017766-3552-493c-a36d-55f60a9370f6)

Would you change something else in its style ?

**Comment by neilimixamo** [comment]
badge size increased a little bit

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/9d87582d-24b7-43f4-a54b-6bc793763aad)

**Comment by hAMMERlized** [comment]
Looks perfect. I think the upper size looks better, cleaner. But it's up to you. I will resize it by myself, all good.

Does the badge disaper when e.g. no lights are turned on or will it display a "0"? I think it would be nice if it disappears?

**Comment by neilimixamo** [comment]
Badge won't show up when "off"

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/4f27ec94-13e9-4ab2-a318-aa7309648213)
